name: Lint

on: push # TODO: activate for pushes into main and for pull requests only
  # # Trigger the workflow on push or pull request,
  # # but only for the main branch
  # push:
  #   branches:
  #     - main
  # # Replace pull_request with pull_request_target if you
  # # plan to use this action with forks, see the Limitations section
  # pull_request:
  #   branches:
  #     - main

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
# permissions:
#   checks: write
#   contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2  # checkout the repository content to github runner.

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install black
      
      # Run commands
      - name: Run linter
        run: make lint_code
